(() => {
  "use strict";
  const params=new URLSearchParams(location.search), reading=window.hubReadings[params.get("reading")||"community-garden"];
  if(!reading){location.replace("reading-library.html");return;}
  let user,progressMap=new Map(),activeStage,startedAt=Date.now();
  const $=selector=>document.querySelector(selector);
  const safe=value=>{const node=document.createElement("span");node.textContent=value??"";return node.innerHTML;};
  const updateMetacognitionCopy=root=>{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(walker.nextNode())walker.currentNode.nodeValue=walker.currentNode.nodeValue.replace(/\bReflection\b/g,"Metacognition").replace(/\breflection\b/g,"metacognition");};
  new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===Node.ELEMENT_NODE)updateMetacognitionCopy(node);}))).observe(document.body,{childList:true,subtree:true});
  updateMetacognitionCopy(document.body);
  const eagleProgressImages=["progrees1.png","progress2.png","progress3.png","progress4.png","progress5.png","progress6.png","progress7.png","progress8.png","progress9.png","progress10.png"];
  async function enhanceReadingCelebration(celebration){if(!celebration||celebration.classList.contains("eagle-celebration-ready"))return;celebration.classList.add("eagle-celebration-ready");let completedCount=1;try{const {count,error}=await window.supabaseClient.from("student_readings").select("id",{count:"exact",head:true}).eq("student_id",user.id).eq("status","completed");if(error)throw error;completedCount=Math.max(1,Number(count)||1);}catch(error){console.error("Eagle progress count error",error);}const stage=Math.min(completedCount,10),image=eagleProgressImages[stage-1];celebration.innerHTML=`<div class="fireworks" aria-hidden="true">${Array.from({length:28},(_,index)=>`<i style="--x:${(index*37)%100}%;--dx:${(index-14)*7}px;--dy:${-110-(index%5)*24}px;--delay:${(index%7)*.12}s"></i>`).join("")}</div><span class="badge">New Eagle Stage Unlocked!</span><img class="celebration-eagle" src="assets/images/progress/${image}" alt="New eagle growth stage ${stage}"><h2>Reading Journey Completed!</h2><p>You completed <strong>${safe(reading.title)}</strong> and helped your eagle grow.</p><p class="eagle-stage-label">Eagle stage ${stage} of 10</p><div class="celebration-actions"><a class="btn btn-primary" href="student-dashboard.html">See My Progress →</a><a class="btn btn-secondary" href="reading-library.html">Choose Another Reading</a></div>`;}
  new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType!==Node.ELEMENT_NODE)return;const celebration=node.matches?.(".journey-celebration")?node:node.querySelector?.(".journey-celebration");if(celebration)enhanceReadingCelebration(celebration);}))).observe(document.body,{childList:true,subtree:true});
  const label=status=>status==="completed"?"Completed":status==="started"?"In progress":"Not started";
  function nextPending(){return reading.stages.find(stage=>progressMap.get(stage.id)?.status!=="completed")||reading.stages[reading.stages.length-1];}
  function setupComprehensionQuiz(stage){const selections=new Map(),buttons=[...$("#stagePanel").querySelectorAll("[data-quiz-choice]")],check=$("[data-check-quiz]");buttons.forEach(button=>button.onclick=()=>{const [questionIndex,optionIndex]=button.dataset.quizChoice.split(":").map(Number);$("#stagePanel").querySelectorAll(`[data-quiz-choice^="${questionIndex}:"]`).forEach(item=>item.classList.remove("selected"));button.classList.add("selected");selections.set(questionIndex,optionIndex);check.disabled=selections.size!==(stage.content.questions||[]).length;});check.onclick=async()=>{check.disabled=true;try{const results=await Promise.all([...selections.entries()].sort((a,b)=>a[0]-b[0]).map(async([questionIndex,optionIndex])=>{const {data,error}=await window.supabaseClient.rpc("check_reading_answer",{target_activity_id:stage.id,selected_option:questionIndex*10+optionIndex});if(error)throw error;return {questionIndex,correct:Boolean(data?.correct)};}));results.forEach(({questionIndex,correct})=>{const selected=$("#stagePanel").querySelector(`[data-quiz-choice="${questionIndex}:${selections.get(questionIndex)}"]`);selected.classList.add(correct?"answer-correct":"answer-incorrect");});const correct=results.filter(result=>result.correct).length;showMessage(`You answered ${correct} of 3 questions correctly.`,correct>=2);setTimeout(()=>completeStage(stage,Math.round(correct/3*100),3,null,`${correct} of 3 answers correct.`),1400);}catch(error){console.error("Comprehension check error",error);showMessage("We could not check your answers. Please try again.",false);check.disabled=false;}};}
  function setupVocabularyCards(stage){let matched=0,totalAttempts=0;const cards=[...$("#stagePanel").querySelectorAll("[data-vocabulary-card]")];cards.forEach(card=>{const wordIndex=Number(card.dataset.vocabularyCard),select=card.querySelector("select"),button=card.querySelector("button"),feedback=card.querySelector(".vocabulary-card-feedback");select.onchange=()=>{button.disabled=select.value==="";feedback.textContent="";card.classList.remove("incorrect");};button.onclick=async()=>{button.disabled=true;totalAttempts+=1;try{const {data,error}=await window.supabaseClient.rpc("check_reading_answer",{target_activity_id:stage.id,selected_option:wordIndex*10+Number(select.value)});if(error)throw error;if(data?.correct){card.classList.add("matched");card.classList.remove("incorrect");select.disabled=true;feedback.textContent="✓ Correct match";matched+=1;$("#matchProgress").textContent=`${matched} of 10 words matched`;if(matched===10){const score=Math.round(10/totalAttempts*100);setTimeout(()=>completeStage(stage,score,totalAttempts,null,"All 10 words matched!"),600);}}else{card.classList.add("incorrect");feedback.textContent=data?.feedback||"Not quite. Choose a different meaning.";button.disabled=false;}}catch(error){console.error("Vocabulary card error",error);feedback.textContent="We could not check this match. Please try again.";card.classList.add("incorrect");button.disabled=false;}};});}
  function setupCollaborationForum(stage){const host=$("#collaborationForum");const starterOptions=["I agree with your idea because…","I have a different perspective because…","Your idea made me think about…","Another example from the reading is…"];
    const validate=text=>{const clean=String(text||"").trim();if(clean.length<10||clean.length>500)return "Write between 10 and 500 characters.";if(/https?:\/\/|www\./i.test(clean))return "Links are not allowed in this activity.";return "";};
    async function load(){host.innerHTML='<p class="auth-message loading">Loading your group forum…</p>';const {data,error}=await window.supabaseClient.rpc("get_collaboration_forum",{target_reading_id:reading.id});if(error){console.error("Forum load error",error);host.innerHTML='<p class="auth-message error">We could not load your group forum. Please try again.</p>';return;}const posts=data?.posts||[];host.innerHTML=`<div class="forum-privacy-note">Only learners in <strong>${safe(data?.className||"your group")}</strong> can see these ideas. Do not share personal information.</div>${data?.ownPost?`<article class="forum-own-post"><span class="badge">Your idea</span><p>${safe(data.ownPost.idea)}</p></article>`:`<form id="forumIdeaForm" class="forum-compose"><label for="forumIdea">Share an idea or perspective inspired by the reading.</label><textarea id="forumIdea" name="idea" minlength="10" maxlength="500" required></textarea><div class="forum-form-footer"><small>10–500 characters · No links or personal information</small><button class="btn btn-primary">Share My Idea</button></div></form>`}<section class="forum-perspectives"><h3>Classmate perspectives</h3>${posts.length?posts.map(post=>`<article class="forum-post"><header><strong>${safe(post.displayName||"Classmate")}</strong><span>${Number(post.replyCount)||0} ${(Number(post.replyCount)||0)===1?"reply":"replies"}</span></header><p>${safe(post.idea)}</p>${(post.replies||[]).length?`<div class="forum-replies">${post.replies.map(reply=>`<p><strong>${safe(reply.displayName||"Classmate")}:</strong> ${safe(reply.reply)}</p>`).join("")}</div>`:""}${post.repliedByMe?'<span class="forum-complete-mark">You responded to this idea.</span>':`<form class="forum-reply-form" data-post-id="${safe(post.id)}"><label>Respond with your perspective</label><select name="starter">${starterOptions.map(option=>`<option>${option}</option>`).join("")}</select><textarea name="reply" minlength="10" maxlength="500" required></textarea><button class="btn btn-secondary">Post Response</button></form>`}</article>`).join(""):'<p class="empty-state">No classmate ideas are available yet. Return after a classmate shares an idea.</p>'}</section><p class="forum-requirements"><span class="${data?.hasOwnPost?"done":""}">✓ Share your idea</span><span class="${data?.hasReplied?"done":""}">✓ Respond to a classmate</span></p>`;
      $("#forumIdeaForm")?.addEventListener("submit",async event=>{event.preventDefault();const idea=new FormData(event.currentTarget).get("idea"),message=validate(idea);if(message){showMessage(message,false);return;}const button=event.currentTarget.querySelector("button");button.disabled=true;const result=await window.supabaseClient.rpc("publish_collaboration_idea",{target_reading_id:reading.id,idea_text:String(idea).trim()});if(result.error){console.error("Forum publish error",result.error);showMessage("We could not share your idea. Please try again.",false);button.disabled=false;return;}showMessage("Your idea was shared with your group.",true);await load();});
      host.querySelectorAll(".forum-reply-form").forEach(form=>form.addEventListener("submit",async event=>{event.preventDefault();const values=new FormData(form),reply=`${values.get("starter")} ${values.get("reply")}`.trim(),message=validate(reply);if(message){showMessage(message,false);return;}const button=form.querySelector("button");button.disabled=true;const result=await window.supabaseClient.rpc("reply_to_collaboration_idea",{target_post_id:form.dataset.postId,reply_text:reply});if(result.error){console.error("Forum reply error",result.error);showMessage("We could not post your response. Please try again.",false);button.disabled=false;return;}showMessage("You shared your perspective. Collaboration complete!",true);setTimeout(()=>completeStage(stage,100,2,null,"You shared an idea and responded to a classmate."),1200);}));
    }load();}
  function updateHeader(){const done=reading.stages.filter(stage=>progressMap.get(stage.id)?.status==="completed").length,pct=Math.round(done/reading.stages.length*100);$("#journeyProgressBar").style.width=`${pct}%`;$("#journeyProgressText").textContent=`${done} of ${reading.stages.length} stages completed · ${pct}%`;$("#stageNav").innerHTML=reading.stages.map(stage=>`<button data-stage="${stage.slug}" class="${stage.slug===activeStage?.slug?"active":""}"><span>${stage.title}</span><small>${label(progressMap.get(stage.id)?.status)}</small></button>`).join("");$("#stageNav").querySelectorAll("button").forEach(button=>button.onclick=()=>showStage(reading.stages.find(stage=>stage.slug===button.dataset.stage)));}
  async function updateJourney(stage,status="started") {const now=new Date().toISOString();const {error}=await window.supabaseClient.from("student_readings").upsert({student_id:user.id,reading_id:reading.id,status,current_activity_id:stage.id,started_at:now,updated_at:now},{onConflict:"student_id,reading_id"});if(error)throw error;}
  function stageBody(stage){
    if(stage.type==="match")return `<span class="badge">Vocabulary</span><h2>${stage.content.prompt}</h2><p>Choose the meaning that matches each word.</p><div class="vocabulary-card-list">${(stage.content.words||[]).map((word,wordIndex)=>`<article class="vocabulary-horizontal-card" data-vocabulary-card="${wordIndex}"><img src="${stage.images?.[wordIndex]||"assets/icons/book.svg"}" alt=""><div class="vocabulary-card-word"><small>Word ${wordIndex+1}</small><strong>${word}</strong></div><div class="vocabulary-card-answer"><label for="meaning-${wordIndex}">Meaning</label><select id="meaning-${wordIndex}"><option value="">Choose a meaning…</option>${(stage.content.definitions||[]).map((definition,definitionIndex)=>`<option value="${definitionIndex}">${definition}</option>`).join("")}</select><span class="vocabulary-card-feedback" aria-live="polite"></span></div><button type="button" class="btn btn-secondary" disabled>Check</button></article>`).join("")}</div><p id="matchProgress" class="match-progress">0 of 10 words matched</p>`;
    if(stage.type==="forum")return `<span class="badge">Collaboration Forum</span><h2>Share ideas and perspectives</h2><p>Complete this stage by sharing one idea and responding respectfully to a different classmate.</p><div id="collaborationForum"></div>`;
    if(stage.type==="quiz")return `<span class="badge">Reading Comprehension</span><h2>Show what you understood</h2><p>Answer all three questions about the reading.</p><div class="comprehension-quiz">${(stage.content.questions||[]).map((question,questionIndex)=>`<fieldset class="comprehension-question" data-question="${questionIndex}"><legend>${questionIndex+1}. ${question.prompt}</legend><div class="journey-options">${question.options.map((option,optionIndex)=>`<button type="button" data-quiz-choice="${questionIndex}:${optionIndex}">${option}</button>`).join("")}</div></fieldset>`).join("")}</div><button class="btn btn-primary" data-check-quiz disabled>Check My Answers</button>`;
    if(stage.type==="prediction")return `<span class="badge">Before Reading</span><h2>Look closely and make a prediction</h2><p>Study the image, then choose the answer that best matches what you notice.</p><figure class="before-reading-image"><img src="${stage.image}" alt="Children participating in a community activity"></figure><h3 class="before-reading-question">${stage.content.prompt}</h3><div class="journey-options">${(stage.content.options||[]).map((option,index)=>`<button type="button" data-choice="${index}">${option}</button>`).join("")}</div><button class="btn btn-primary" data-check disabled>Check My Answer</button>`;
    if(stage.type==="text")return `<span class="badge">Read the Text</span><h2>${reading.title}</h2><div class="reading-text">${String(stage.content.text||"").split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>`<p>${line}</p>`).join("")}</div><button class="btn btn-primary" data-complete>I'm Done Reading →</button>`;
    if(stage.type==="match")return `<span class="badge">Vocabulary</span><h2>${stage.content.prompt}</h2><p>Select one word, then select its meaning.</p><div class="vocabulary-match"><div><h3>Words</h3><div class="match-list vocabulary-word-list">${(stage.content.words||[]).map((word,index)=>`<button type="button" data-word-index="${index}"><img src="${stage.images?.[index]||"assets/icons/book.svg"}" alt=""><span>${word}</span></button>`).join("")}</div></div><div><h3>Meanings</h3><div class="match-list">${(stage.content.definitions||[]).map((definition,index)=>`<button type="button" data-definition-index="${index}">${definition}</button>`).join("")}</div></div></div><p id="matchProgress" class="match-progress">0 of 10 words matched</p>`;
    if(stage.type==="choice")return `<span class="badge">${stage.title}</span><h2>${stage.content.prompt}</h2><div class="journey-options">${(stage.content.options||[]).map((option,index)=>`<button type="button" data-choice="${index}">${option}</button>`).join("")}</div><button class="btn btn-primary" data-check disabled>Check and Continue</button>`;
    if(stage.type==="reflection")return `<span class="badge">Reflection</span><h2>Think about your journey</h2><form id="journeyReflection"><label>What did you learn?<textarea name="learned" maxlength="400" required></textarea></label><label>What part was easiest?<textarea name="easiest" maxlength="300" required></textarea></label><label>What part was challenging?<textarea name="challenging" maxlength="300" required></textarea></label><label>How confident do you feel?<select name="confidence"><option value="1">I need help</option><option value="2">I am learning</option><option value="3">I can do it</option><option value="4">I can explain it</option></select></label><button class="btn btn-primary">Finish My Reading Journey</button></form>`;
    return '<p class="auth-message error">This stage is not available.</p>';
  }
  async function showStage(stage){activeStage=stage;startedAt=Date.now();history.replaceState(null,"",`reading-journey.html?reading=${reading.id}&stage=${stage.slug}`);$("#stagePanel").innerHTML='<p class="auth-message loading">Loading this stage…</p>';try{if(stage.type!=="reflection"&&!stage.content){const {data,error}=await window.supabaseClient.rpc("get_reading_stage_content",{target_activity_id:stage.id});if(error)throw error;stage.content=data||{};}$("#stagePanel").innerHTML=stageBody(stage)+'<p id="stageMessage" class="auth-message" role="status"></p>';updateHeader();if(progressMap.get(stage.id)?.status!=="completed"){await window.hubProgress.saveActivityProgress({activityId:stage.id,status:"started",attempts:0,timeSpentSeconds:0});progressMap.set(stage.id,{...(progressMap.get(stage.id)||{}),status:"started"});await updateJourney(stage);updateHeader();}}catch(error){console.error("Stage start error",error);$("#stagePanel").innerHTML='<p class="auth-message error">We could not securely load this stage. Please try again.</p>';return;}
    let selected=null;$("#stagePanel").querySelectorAll("[data-choice]").forEach(button=>button.onclick=()=>{$("#stagePanel").querySelectorAll("[data-choice]").forEach(item=>item.classList.remove("selected"));button.classList.add("selected");selected=Number(button.dataset.choice);$("[data-check]").disabled=false;});
    if(stage.type==="match")setupVocabularyCards(stage);
    if(stage.type==="reflection"){
      const confidenceFaces=["😟  I need help","😐  I am learning","🙂  I can do it","😄  I can explain it"];
      const metacognitionForm=$("#journeyReflection"),labels=metacognitionForm?.querySelectorAll("label");
      if(labels?.[0]?.firstChild)labels[0].firstChild.nodeValue="What did I learn?";
      if(labels?.[3]?.firstChild)labels[3].firstChild.nodeValue="How confident do I feel?";
      metacognitionForm?.querySelectorAll('select[name="confidence"] option').forEach((option,index)=>{option.textContent=confidenceFaces[index];});
    }
    if(stage.type==="quiz")setupComprehensionQuiz(stage);
    if(stage.type==="forum")setupCollaborationForum(stage);
    $("[data-check]")?.addEventListener("click",async()=>{const button=$("[data-check]");button.disabled=true;try{const {data,error}=await window.supabaseClient.rpc("check_reading_answer",{target_activity_id:stage.id,selected_option:selected});if(error)throw error;if(data?.correct){await completeStage(stage,100,1,null,data.feedback);return;}showMessage(data?.feedback||"Not quite. Try another answer.",false);selected=null;$("#stagePanel").querySelectorAll("[data-choice]").forEach(item=>item.classList.remove("selected"));button.disabled=true;}catch(error){console.error("Answer check error",error);showMessage("We could not check this answer. Please try again.",false);button.disabled=false;}});
    $("[data-complete]")?.addEventListener("click",()=>completeStage(stage,null,1));
    $("#journeyReflection")?.addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget),text=`Learned: ${data.get("learned")}\nEasiest: ${data.get("easiest")}\nChallenging: ${data.get("challenging")}`;const reflection=await window.hubProgress.saveReflection({activityId:stage.id,reflectionText:text,confidenceLevel:Number(data.get("confidence"))});if(!reflection.ok){showMessage(reflection.message,false);return;}await completeStage(stage,null,1,Number(data.get("confidence")));});
  }
  function setupVocabularyMatch(stage){let selectedWord=null,matched=0,totalAttempts=0;const words=[...$("#stagePanel").querySelectorAll("[data-word-index]")],definitions=[...$("#stagePanel").querySelectorAll("[data-definition-index]")];words.forEach(button=>button.onclick=()=>{if(button.disabled)return;words.forEach(item=>item.classList.remove("selected"));button.classList.add("selected");selectedWord=button;showMessage(`Now choose the meaning of “${button.textContent}”.`);});definitions.forEach(button=>button.onclick=async()=>{if(!selectedWord||button.disabled){showMessage("Choose a word first.",false);return;}definitions.forEach(item=>item.classList.remove("selected"));button.classList.add("selected");const wordIndex=Number(selectedWord.dataset.wordIndex),definitionIndex=Number(button.dataset.definitionIndex);totalAttempts+=1;try{const {data,error}=await window.supabaseClient.rpc("check_reading_answer",{target_activity_id:stage.id,selected_option:wordIndex*10+definitionIndex});if(error)throw error;if(data?.correct){selectedWord.disabled=true;button.disabled=true;selectedWord.classList.add("matched");button.classList.add("matched");matched+=1;$("#matchProgress").textContent=`${matched} of 10 words matched`;showMessage(data.feedback,true);selectedWord=null;if(matched===10){const score=Math.round(10/totalAttempts*100);setTimeout(()=>completeStage(stage,score,totalAttempts,null,"All 10 words matched!"),500);}}else{showMessage(data?.feedback||"Not quite. Try again.",false);button.classList.remove("selected");}}catch(error){console.error("Vocabulary match error",error);showMessage("We could not check that match. Please try again.",false);}});}
  function showMessage(message,good=true){const host=$("#stageMessage");host.textContent=message;host.className=`auth-message ${good?"success":"error"}`;}
  async function completeStage(stage,score,attempts,confidence=null,answerFeedback=""){const saved=await window.hubProgress.saveActivityProgress({activityId:stage.id,status:"completed",score,attempts,confidenceLevel:confidence,timeSpentSeconds:Math.round((Date.now()-startedAt)/1000)});if(!saved.ok){showMessage(saved.message,false);return;}progressMap.set(stage.id,{status:"completed",score});const next=nextPending();await updateJourney(next,next.id===stage.id?"completed":"started");const {data:completion,error}=await window.supabaseClient.rpc("complete_reading_journey",{target_reading_id:reading.id});if(error)console.error("Completion check error",error);updateHeader();if(completion?.completed){$("#stagePanel").innerHTML='<div class="journey-celebration" role="status"><span aria-hidden="true">🏅</span><h2>Reading Journey Completed!</h2><p>You earned the Community Garden Explorer medal.</p><a class="btn btn-primary" href="student-dashboard.html">See My Dashboard →</a></div>';return;}showMessage(answerFeedback||"Great work! This stage is complete.",score!==0);setTimeout(()=>showStage(next),1600);}
  document.addEventListener("hub:auth-ready",async event=>{user=event.detail.user;$("#journeyContent").hidden=false;$("#journeyTheme").textContent=reading.theme;$("#journeyTitle").textContent=reading.title;$("#journeyDescription").textContent=reading.description;$("#journeyImage").src=reading.image;try{const {data,error}=await window.supabaseClient.from("student_progress").select("activity_id,status,score,confidence_level").eq("student_id",user.id).in("activity_id",reading.stages.map(stage=>stage.id));if(error)throw error;(data||[]).forEach(item=>progressMap.set(item.activity_id,item));const requested=reading.stages.find(stage=>stage.slug===params.get("stage"));showStage(requested||nextPending());}catch(error){console.error("Journey load error",error);$("#stagePanel").innerHTML='<p class="auth-message error">We could not load your journey. Please return to the library and try again.</p>';}});
})();
