(() => {
  "use strict";
  const catalog=Object.values(window.hubReadings),progressByReading=new Map(),journeys=new Map();
  let activeTheme="all";
  const safe=value=>{const node=document.createElement("span");node.textContent=value??"";return node.innerHTML;};
  function card(reading){const percent=progressByReading.get(reading.id)||0,journey=journeys.get(reading.id);const state=percent===100?"Completed":journey?"Making progress":"Ready to explore",button=percent===100?"Read Again":journey?"Continue Journey":"Start Journey";return `<article class="reading-card"><div class="reading-card-image"><img src="${safe(reading.image)}" alt="Reference cover for ${safe(reading.title)}"><span>Available now</span></div><div><span class="badge">${safe(reading.theme)}</span><h2>${safe(reading.title)}</h2><p>${safe(reading.description)}</p><p><strong>${safe(reading.difficulty)}</strong> · About ${reading.minutes} minutes</p><div class="progress-track"><span style="width:${percent}%"></span></div><p>${state} · ${percent}%</p><a class="btn btn-primary" href="reading-journey.html?reading=${encodeURIComponent(reading.id)}">${button} →</a></div></article>`;}
  function render(){const visible=activeTheme==="all"?catalog:catalog.filter(r=>r.theme===activeTheme);document.querySelector("#readingCards").innerHTML=visible.map(card).join("");}
  const themes=["all",...new Set(catalog.map(r=>r.theme))],host=document.querySelector(".reading-filters");host.innerHTML=themes.map(t=>`<button class="${t==="all"?"active":""}" data-theme="${t}">${t==="all"?"All Readings":t}</button>`).join("");host.querySelectorAll("button").forEach(b=>b.onclick=()=>{host.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeTheme=b.dataset.theme;render();});
  document.addEventListener("hub:auth-ready",async event=>{document.querySelector("#libraryContent").hidden=false;try{const user=event.detail.user,[jr,pr]=await Promise.all([window.supabaseClient.from("student_readings").select("reading_id,status").eq("student_id",user.id),window.supabaseClient.from("student_progress").select("status,activities!inner(reading_id,is_required)").eq("student_id",user.id).eq("status","completed")]);if(jr.error)throw jr.error;if(pr.error)throw pr.error;(jr.data||[]).forEach(x=>journeys.set(x.reading_id,x));catalog.forEach(r=>{const count=(pr.data||[]).filter(x=>x.activities?.reading_id===r.id).length;progressByReading.set(r.id,Math.round(count/r.stages.length*100));});render();document.querySelector("#libraryStatus").textContent="Explore 10 complete Reading Journeys.";document.querySelector("#libraryStatus").className="dashboard-status success";}catch(error){console.error("Library error",error);document.querySelector("#libraryStatus").textContent="We could not load your reading progress. Please try again.";render();}});
  if(window.hubCurrentUser)document.dispatchEvent(new CustomEvent("hub:auth-ready",{detail:window.hubCurrentUser}));
})();
