create table if not exists public.student_answer_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  activity_id text not null references public.activities(id) on delete cascade,
  question_index integer not null default 0 check (question_index >= 0),
  selected_option_index integer not null check (selected_option_index >= 0),
  question_prompt text not null,
  selected_answer_text text not null,
  correct_answer_text text not null,
  is_correct boolean not null,
  attempted_at timestamptz not null default now()
);

create index if not exists student_answer_attempts_student_activity_idx
  on public.student_answer_attempts(student_id, activity_id, attempted_at desc);

alter table public.student_answer_attempts enable row level security;
revoke all on table public.student_answer_attempts from anon, authenticated;
revoke all on sequence public.student_answer_attempts_id_seq from anon, authenticated;

create or replace function public.check_reading_answer(
  target_activity_id text,
  selected_option integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  content_data jsonb;
  keys jsonb;
  activity_kind text;
  question_index integer;
  option_index integer;
  expected integer;
  answer_is_correct boolean;
  prompt_text text;
  selected_text text;
  correct_text text;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;

  if target_activity_id = 'community-garden-before-reading' then
    content_data := jsonb_build_object(
      'prompt', 'What do you think the children are doing together?',
      'options', jsonb_build_array(
        'Waiting alone for a bus.',
        'Working together on a community project.',
        'Shopping inside a grocery store.'
      )
    );
    keys := '[1]'::jsonb;
    activity_kind := 'before_reading';
  else
    select stored.content, stored.correct_answers, activity.activity_type
    into content_data, keys, activity_kind
    from public.reading_activity_content as stored
    join public.activities as activity on activity.id = stored.activity_id
    where stored.activity_id = target_activity_id;
  end if;

  if keys is null and target_activity_id = 'community-garden-vocabulary' then
    content_data := public.get_reading_stage_content(target_activity_id);
    keys := '[7,3,9,5,1,8,4,0,6,2]'::jsonb;
    activity_kind := 'vocabulary';
  end if;

  if keys is null then
    return public.check_reading_answer_without_before_reading(target_activity_id, selected_option);
  end if;

  if activity_kind in ('vocabulary', 'reading_comprehension') then
    question_index := selected_option / 10;
    option_index := selected_option % 10;
  else
    question_index := 0;
    option_index := selected_option;
  end if;

  if question_index < 0 or question_index >= jsonb_array_length(keys) then
    raise exception 'Invalid answer';
  end if;

  expected := (keys->>question_index)::integer;
  answer_is_correct := option_index = expected;

  if activity_kind = 'vocabulary' then
    prompt_text := 'Word: ' || coalesce(content_data->'words'->>question_index, 'Vocabulary item');
    selected_text := content_data->'definitions'->>option_index;
    correct_text := content_data->'definitions'->>expected;
  elsif activity_kind = 'reading_comprehension' then
    prompt_text := content_data->'questions'->question_index->>'prompt';
    selected_text := content_data->'questions'->question_index->'options'->>option_index;
    correct_text := content_data->'questions'->question_index->'options'->>expected;
  else
    prompt_text := content_data->>'prompt';
    selected_text := content_data->'options'->>option_index;
    correct_text := content_data->'options'->>expected;
  end if;

  if selected_text is null then raise exception 'Invalid answer option'; end if;

  insert into public.student_answer_attempts (
    student_id, activity_id, question_index, selected_option_index,
    question_prompt, selected_answer_text, correct_answer_text, is_correct
  )
  values (
    auth.uid(), target_activity_id, question_index, option_index,
    coalesce(prompt_text, 'Question'), selected_text,
    coalesce(correct_text, 'Correct answer unavailable'), answer_is_correct
  );

  return jsonb_build_object(
    'correct', answer_is_correct,
    'feedback', case when answer_is_correct
      then 'Correct! The reading supports your answer.'
      else 'Not quite. Review the options and try again.'
    end
  );
end
$$;

revoke all on function public.check_reading_answer(text, integer) from public;
grant execute on function public.check_reading_answer(text, integer) to authenticated;

create or replace function public.educator_get_student_answer_history(
  target_student_id uuid,
  target_reading_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;

  if not exists (
    select 1
    from public.classes as learning_class
    join public.class_members as member on member.class_id = learning_class.id
    where learning_class.teacher_id = auth.uid()
      and learning_class.is_active = true
      and member.student_id = target_student_id
  ) then
    raise exception 'You cannot view this learner';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'activityId', attempt.activity_id,
        'activityTitle', activity.title,
        'activityType', activity.activity_type,
        'questionIndex', attempt.question_index,
        'prompt', attempt.question_prompt,
        'selectedAnswer', attempt.selected_answer_text,
        'correctAnswer', attempt.correct_answer_text,
        'isCorrect', attempt.is_correct,
        'attemptedAt', attempt.attempted_at
      )
      order by activity.activity_order, attempt.question_index, attempt.attempted_at
    ),
    '[]'::jsonb
  )
  into result
  from public.student_answer_attempts as attempt
  join public.activities as activity on activity.id = attempt.activity_id
  where attempt.student_id = target_student_id
    and activity.reading_id = target_reading_id;

  return result;
end
$$;

revoke all on function public.educator_get_student_answer_history(uuid, text) from public;
grant execute on function public.educator_get_student_answer_history(uuid, text) to authenticated;
